# Generated by Django 6.1 on 2026-09-02 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(db_index=True, max_length=255)),
                ('module', models.CharField(choices=[('dns_scan', 'DNS recon'), ('network_intel', 'Network intel'), ('image_osint', 'Image OSINT'), ('email_osint', 'Email OSINT'), ('username_osint', 'Username OSINT')], db_index=True, max_length=32)),
                ('analyst_note', models.TextField(blank=True, default='')),
                ('report_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Analiz',
                'verbose_name_plural': 'Analizler',
                'db_table': 'analiz',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnalizItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=512)),
                ('value', models.TextField()),
                ('analiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.analiz')),
            ],
            options={
                'verbose_name': 'Analiz maddesi',
                'verbose_name_plural': 'Analiz maddeleri',
                'db_table': 'analiz_item',
            },
        ),
    ]
